// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtA1r2SMUldsvazVOgicqk7TMI5Tq_GOA',
    appId: '1:847210502911:web:c8f4e629caed6327874aca',
    messagingSenderId: '847210502911',
    projectId: 'ccstudy-f84d3',
    authDomain: 'ccstudy-f84d3.firebaseapp.com',
    storageBucket: 'ccstudy-f84d3.appspot.com',
    measurementId: 'G-0RB8RMJCV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDijrmw6OZYS2ZUcI9CYn9G3ItC9HbJ4GY',
    appId: '1:847210502911:android:58b1c0b23e211b03874aca',
    messagingSenderId: '847210502911',
    projectId: 'ccstudy-f84d3',
    storageBucket: 'ccstudy-f84d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu5Cwi2RtNAkIa37UF_UeFAEC4njPeaVg',
    appId: '1:847210502911:ios:377cd2a9322c39bc874aca',
    messagingSenderId: '847210502911',
    projectId: 'ccstudy-f84d3',
    storageBucket: 'ccstudy-f84d3.appspot.com',
    iosClientId: '847210502911-v6jo7pais69dcjl89dlimc5cn8guvnca.apps.googleusercontent.com',
    iosBundleId: 'com.example.ccsstudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu5Cwi2RtNAkIa37UF_UeFAEC4njPeaVg',
    appId: '1:847210502911:ios:214b21116c83acb4874aca',
    messagingSenderId: '847210502911',
    projectId: 'ccstudy-f84d3',
    storageBucket: 'ccstudy-f84d3.appspot.com',
    iosClientId: '847210502911-nbjqhd5glo4ujkm64156rq436o8d7s3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.ccsstudy.RunnerTests',
  );
}
